name: Update LeetCode README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test step
        run: echo "Workflow funcionando!"